- hosts: compute_condo
  gather_facts: no
  become: false
  strategy: free

  tasks:
  - name: cp slurm.conf to node
    copy: src="{{playbook_dir}}/roles/slurmctld/files/slurm.conf.condo" dest=/etc/slurm/slurm.conf mode=0644

- hosts: slurm-condo
  gather_facts: no
  become: false
  strategy: free

  tasks:
  - name: cp slurm.conf to node
    copy: src="{{playbook_dir}}/roles/slurmctld/files/slurm.conf.condo" dest=/etc/slurm/slurm.conf mode=0644
