- name: install infiniband support
  yum:
    name: 
      - "@InfiniBand Support"
      - perftest
      - infiniband-diags
    state: present
    use_backend: yum

- name: add mlx driver to boot up
  shell: dracut --add-drivers "mlx4_en mlx4_ib mlx5_ib" -f

- name: start and eable rdma service
  service: name=rdma state=started enabled=yes

- name: put in ifcfg-ib0 file
  template: src=ifcfg-ib0.j2 dest=/etc/sysconfig/network-scripts/ifcfg-ib0 mode=0644

- name: ifup ib0 interface
  shell: ifdown ib0 && ifup ib0
