- command: uname -r
  register: uname

- lineinfile: 
    path: /etc/yum.conf
    state: absent
    regexp: '^exclude=kernel'

- name: install gcc and kernel-devel
  yum: 
    name:
      - kernel-devel-{{ uname.stdout }}
      - gcc
    state: present
    use_backend: yum

- name: copy beegfs rpm to host
  copy: src={{ item }} dest=/usr/local/src/   
  with_items:
    - "/usr/local/src/beegfs-client-7.1.3-el7.noarch.rpm"
    - "/usr/local/src/beegfs-client-compat-7.1.3-el7.noarch.rpm"
    - "/usr/local/src/beegfs-common-7.1.3-el7.noarch.rpm"
    - "/usr/local/src/beegfs-debuginfo-7.1.3-el7.x86_64.rpm"
    - "/usr/local/src/beegfs-helperd-7.1.3-el7.x86_64.rpm"
    - "/usr/local/src/beegfs-utils-7.1.3-el7.x86_64.rpm"
    - "/usr/local/src/libbeegfs-ib-7.1.3-el7.x86_64.rpm"

- name: install beegfs client rpm
  yum: 
    name: 
      - "/usr/local/src/beegfs-client-7.1.3-el7.noarch.rpm"
      - "/usr/local/src/beegfs-client-compat-7.1.3-el7.noarch.rpm"
      - "/usr/local/src/beegfs-common-7.1.3-el7.noarch.rpm"
      - "/usr/local/src/beegfs-debuginfo-7.1.3-el7.x86_64.rpm"
      - "/usr/local/src/beegfs-helperd-7.1.3-el7.x86_64.rpm"
      - "/usr/local/src/beegfs-utils-7.1.3-el7.x86_64.rpm"
      - "/usr/local/src/libbeegfs-ib-7.1.3-el7.x86_64.rpm"
    state: present
    use_backend: yum

- lineinfile: dest=/etc/beegfs/beegfs-client.conf regexp='^sysMgmtdHost' line='sysMgmtdHost = {{ mgmtd_hostname }}'

- lineinfile: dest=/etc/beegfs/beegfs-client.conf regexp='^connInterfacesFile' line='connInterfacesFile = /etc/beegfs/interface'

- lineinfile: dest=/etc/beegfs/beegfs-client.conf regexp='^quotaEnabled' line='quotaEnabled = true'      
  when: quota|bool
  
- lineinfile: dest=/etc/beegfs/interface line='ib0' create=yes
#  when: ansible_ib0.device is defined

#- lineinfile: dest=/etc/beegfs/interface line='{{ item }}' create=yes
#  when: ansible_{{ item }}.device is defined
#  with_items: "{{ network_interface }}"

- lineinfile: dest=/etc/beegfs/beegfs-mounts.conf regexp='^/mnt/beegfs' line='{{ mount_point }} /etc/beegfs/beegfs-client.conf'

#- lineinfile: dest=/etc/beegfs/beegfs-client-autobuild.conf regexp='^buildArgs=' line='buildArgs=-j8'
#  when: ansible_ib0.device is undefined

- lineinfile: dest=/etc/beegfs/beegfs-client-autobuild.conf regexp='^buildArgs=' line='buildArgs=-j8 BEEGFS_OPENTK_IBVERBS=1 '
#  when: ansible_ib0.device is defined

  
- command: "/etc/init.d/beegfs-client rebuild"  

- service: name={{ item }} state=started enabled=yes
  with_items:
    - beegfs-helperd
    - beegfs-client
