- name: install required rpm
  yum: 
    name:
       - munge
    state: present
    use_backend: yum

- name: copy munge key to host
  copy: src="{{role_path}}/../slurmctld/files/munge.key" dest=/etc/munge/munge.key owner=munge group=munge mode=0600 force=yes

- name: start munge service
  service: name=munge state=started enabled=yes

- name: check if slurm rpm is installed already
  shell: rpm -qa | grep slurm-slurmd-{{ slurm_version}}
  register: rpmqa

- debug:
    var: rpmqa
    verbosity: 1

- name: copy slurm rpm to host
  copy: src={{ item }} dest=/usr/local/src/   
  with_items:
    - "/usr/local/src/slurm-slurmd-{{ slurm_version}}-1.el7.x86_64.rpm"
    - "/usr/local/src/slurm-{{ slurm_version}}-1.el7.x86_64.rpm"
    - "/usr/local/src/slurm-pam_slurm-{{ slurm_version}}-1.el7.x86_64.rpm"
    - "/usr/local/src/slurm-libpmi-{{ slurm_version}}-1.el7.x86_64.rpm"
    - "/usr/local/src/slurm-devel-{{ slurm_version}}-1.el7.x86_64.rpm"
  when: rpmqa.rc != 0

- name: install slurm rpm   
  shell: yum install -y /usr/local/src/slurm*{{ slurm_version}}-1.el7.x86_64.rpm
  when: rpmqa.rc != 0

- name: create /etc/slurm folder
  file:  path=/etc/slurm state=directory mode=0755

- name: create slurmspooldir folder
  file: path={{slurm_spool_dir}} state=directory owner=slurm group=slurm mode=0755 

- name: copy slurm conf file   
  copy: src="{{role_path}}/../slurmctld/files/slurm.conf" dest=/etc/slurm/slurm.conf mode=0644  

- name: start slurmd service   
  service: name=slurmd state=started enabled=yes
  when: " 'login' not in group_names "



 
