- name: copy sh file in /etc/profile.d
  copy: src={{ item }} dest=/etc/profile.d/
  with_items:
    - modules.sh
    - modules.csh
    - z00_StdEnv.sh
    - z00_StdEnv.csh

#- name: put apps mount in /etc/fstab
#  lineinfile: dest=/etc/fstab line='apps:/opt /opt nfs defaults 0 0'
# not a good idea, if nfs mount fail at boot, network will become unreachable,bug??

- name: create /opt/apps dir
  file: path=/opt/apps state=directory 

- name: mount /opt
  mount: 
    path: /opt/apps
    src: apps:/opt/apps
    fstype: nfs 
    opts: ro
    state: mounted
